/**
 * Guard for rendering LLM-generated URLs (e.g. `booking_url` on itinerary
 * items) as clickable links.
 *
 * The itinerary is generated by an LLM prompt that can be influenced by
 * scraped/fetched content or user free text (see
 * docs/scaling-tech-challenges.md, Security Vulnerabilities #4 — prompt
 * injection). A manipulated response could set `booking_url` to a
 * `javascript:`/`data:` URI (XSS) or a convincing phishing domain. Only ever
 * render `http(s)` links with a real hostname.
 */
export function isSafeExternalUrl(url: string | null | undefined): boolean {
  if (!url) return false;
  try {
    const parsed = new URL(url);
    return (parsed.protocol === 'http:' || parsed.protocol === 'https:') && !!parsed.hostname;
  } catch {
    return false;
  }
}
