import type { ItineraryDay, ItineraryItem } from '@/types'

const ITEMS: ItineraryItem[] = [
  {
    id: 'a1',
    time_start: '09:00',
    time_end: '11:00',
    title: 'Senso-ji Temple',
    description: 'Tokyo\'s oldest temple in the heart of Asakusa. Arrive early to beat the crowds and catch the morning light through the Kaminarimon Gate.',
    location: { lat: 35.7148, lon: 139.7967, address: 'Asakusa, Tokyo' },
    tags: ['instaworthy', 'kid_friendly'],
    booking_url: '',
    youtube_video_id: 'dQw4w9WgXcQ',
    alignment_score: 92,
    warnings: [],
  },
  {
    id: 'a2',
    time_start: '11:30',
    time_end: '13:00',
    title: 'Nakamise Shopping Street',
    description: 'A 250-metre covered shopping street leading to Senso-ji, packed with traditional Japanese souvenirs, snacks, and crafts.',
    location: { lat: 35.7138, lon: 139.7963, address: 'Nakamise, Asakusa' },
    tags: ['kid_friendly'],
    booking_url: '',
    youtube_video_id: '',
    alignment_score: 80,
    warnings: [],
  },
  {
    id: 'a3',
    time_start: '13:30',
    time_end: '14:30',
    title: 'Ramen Lunch at Fuunji',
    description: 'Legendary tsukemen (dipping ramen) joint near Shinjuku. Expect a short queue — worth every minute.',
    location: { lat: 35.6950, lon: 139.7036, address: 'Shinjuku, Tokyo' },
    tags: [],
    booking_url: 'https://tabelog.com/tokyo/A1304/A130401/13033450/',
    youtube_video_id: '',
    alignment_score: 88,
    warnings: [],
  },
  {
    id: 'a4',
    time_start: '15:00',
    time_end: '18:00',
    title: 'TeamLab Borderless',
    description: 'Immersive digital art museum in Odaiba. Book tickets in advance — this consistently sells out weeks ahead.',
    location: { lat: 35.6267, lon: 139.7750, address: 'Odaiba, Tokyo' },
    tags: ['instaworthy', 'kid_friendly'],
    booking_url: 'https://borderless.teamlab.art/',
    youtube_video_id: '',
    alignment_score: 96,
    warnings: [],
  },
  {
    id: 'a5',
    time_start: '19:30',
    time_end: '21:30',
    title: 'Shibuya Crossing & Sky View',
    description: 'Watch the world\'s busiest pedestrian crossing from the Shibuya Sky rooftop observation deck at dusk. Reserve the sunset slot.',
    location: { lat: 35.6590, lon: 139.7006, address: 'Shibuya, Tokyo' },
    tags: ['instaworthy'],
    booking_url: 'https://www.shibuya-sky.com/',
    youtube_video_id: '',
    alignment_score: 94,
    warnings: [],
  },
]

const ITEMS_DAY2: ItineraryItem[] = [
  {
    id: 'b1',
    time_start: '08:30',
    time_end: '11:00',
    title: 'Tsukiji Outer Market',
    description: 'Sample fresh sushi, tamagoyaki, and street food at the famous outer market. Still buzzing after the inner market relocated to Toyosu.',
    location: { lat: 35.6655, lon: 139.7707, address: 'Tsukiji, Chuo' },
    tags: ['kid_friendly'],
    booking_url: '',
    youtube_video_id: '',
    alignment_score: 85,
    warnings: [],
  },
  {
    id: 'b2',
    time_start: '11:30',
    time_end: '14:00',
    title: 'Hamarikyu Gardens',
    description: 'Tranquil Edo-period tidal garden surrounded by skyscrapers. Take the water bus from Hinode Pier for the best approach.',
    location: { lat: 35.6598, lon: 139.7626, address: 'Hamarikyu, Chuo' },
    tags: ['kid_friendly', 'instaworthy'],
    booking_url: '',
    youtube_video_id: '',
    alignment_score: 78,
    warnings: [],
  },
  {
    id: 'b3',
    time_start: '15:00',
    time_end: '18:00',
    title: 'Akihabara Electric Town',
    description: 'Tokyo\'s electronics and anime mecca. Multi-floor arcades, retro game shops, and themed cafes line every street.',
    location: { lat: 35.7022, lon: 139.7745, address: 'Akihabara, Tokyo' },
    tags: ['instaworthy'],
    booking_url: '',
    youtube_video_id: '',
    alignment_score: 83,
    warnings: [],
  },
  {
    id: 'b4',
    time_start: '19:00',
    time_end: '21:00',
    title: 'Dinner at Omoide Yokocho',
    description: 'Narrow alley in Shinjuku packed with tiny yakitori bars. Smoke, soy, and atmosphere — this is old Tokyo at its best.',
    location: { lat: 35.6919, lon: 139.7004, address: 'Nishi-Shinjuku, Tokyo' },
    tags: [],
    booking_url: '',
    youtube_video_id: '',
    alignment_score: 90,
    warnings: [],
  },
]

export const MOCK_DAYS: ItineraryDay[] = [
  {
    day_number: 1,
    date: '2026-11-14',
    theme: 'Temples, Tech & Tokyo Nights',
    items: ITEMS,
    transit_warnings: [
      {
        between_items: ['a3', 'a4'],
        message: 'Allow 35 min for the Yamanote → Rinkai line transfer to Odaiba during rush hour.',
      },
    ],
  },
  {
    day_number: 2,
    date: '2026-11-15',
    theme: 'Markets, Gardens & Geek Culture',
    items: ITEMS_DAY2,
    transit_warnings: [],
  },
  {
    day_number: 3,
    date: '2026-11-16',
    theme: 'Day Trip: Nikko Shrines',
    items: [
      {
        id: 'c1',
        time_start: '07:00',
        time_end: '09:30',
        title: 'Shinkansen to Nikko',
        description: 'Take the Tobu Nikko line from Asakusa. A scenic 2-hour journey into the mountains.',
        location: { lat: 36.7583, lon: 139.5997, address: 'Nikko, Tochigi' },
        tags: [],
        booking_url: '',
        youtube_video_id: '',
        alignment_score: 75,
        warnings: [],
      },
      {
        id: 'c2',
        time_start: '10:00',
        time_end: '14:00',
        title: 'Toshogu Shrine Complex',
        description: 'UNESCO World Heritage shrine famous for the "hear no evil, see no evil, speak no evil" monkeys and the sleeping cat carving.',
        location: { lat: 36.7583, lon: 139.5997, address: 'Toshogu, Nikko' },
        tags: ['instaworthy', 'kid_friendly'],
        booking_url: 'https://www.toshogu.jp/english/',
        youtube_video_id: '',
        alignment_score: 95,
        warnings: [],
      },
    ],
    transit_warnings: [],
  },
]
